[package]
name = 'core-packages/shared'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1-rc.18'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.1.0'
