[package]
name = 'core-packages/virtualized-list'
description = 'https://github.com/grilme99/CorePackages'
version = '1.1.2'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.1.0'
Otter = 'grilme99/otter-compat@1.0.0'
Promise = 'evaera/promise@4.0.0'
ReactProxy = 'core-packages/react@17.0.1-rc.16'
