[package]
name = 'core-packages/throat'
description = 'https://github.com/grilme99/CorePackages'
version = '3.1.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.1.0'
Promise = 'evaera/promise@4.0.0'
